### PR TITLE
WIP: Add param wildcard

### PR DESCRIPTION
**Pull request by wolffberg**
Vault has the ability to generate temporary credentials from e.g. AWS IAM.

The current way of pulling secrets prevents the use of temporary credentials as you can only define one field from the secret to import into an environment variable. If you pull `AWS_ACCESS_KEY_ID`,  `AWS_ACCESS_KEY_ID` and `AWS_SESSION_TOKEN` from the same secret you will end up with 3 disconnected values.

This PR enables pulling the whole `data` object (only string values) from a secret (could be the `creds` endpoint of the AWS engine), enabling your pipeline step to parse and use the values itself.

Note that the asterisk has to be quoted for the web request to work.
```yaml
kind: secret
name: aws_credentials
get:
  path: aws/account/creds/role
  name: "*"
```

_**WIP**: Needs testing but would like to have the PR out for input._

### CODE REVIEW

**Comment by jimsheldon** [comment]
@wolffberg can you update the golang image in the build step to 1.17? 1.12 is very old and apparently certificates have expired

**Comment by jimsheldon** [comment]
I can also get that change into the master branch first if you'd rather rebase

**Comment by wolffberg** [comment]
Bumped the build image version to `1.17`.

A few things to consider before merging.

This is potentially a breaking change as Vault allows secret fields with the name `*`.
Should we have another way of specifying that we want all data like a new value in the `secret` kind?

An example could look like this.
```yaml
kind: secret
name: all_data
get:
  path: path/to/secret
  allData: true
```

When we find the good solution we should also make sure to add it to https://docs.drone.io/secret/external/vault/

**Comment by wolffberg** [comment]
During testing it turns out that this change will break the security implemented at https://github.com/drone/drone-vault/blob/master/plugin/plugin.go#L47 as you cannot add custom fields to the AWS secret engine.

**Comment by wolffberg** [comment]
Closing as this will break https://github.com/drone/drone-vault/pull/2.

**Pull request closed without merging**
