### PR TITLE
Integrate multi arch support

### PR DESCRIPTION
**Pull request by tboerger**

### CODE REVIEW

**Comment by djmaze** [comment]
Can we somehow get this merged? Would be really useful to have this running on arm.

**Comment by tboerger** [comment]
I need to apply some comments from brad, but thanks for the reminder :)

**Comment by amritanshu-pandey** [comment]
Can this be merged. It would be great to have arm64 and other architectures support going. Happy to help if required.

**Comment by tboerger** [comment]
@bradrydzewski please check if this could be a proper standard format for you which supports multi arch automated deployments :)

**Pull request closed without merging**
